//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restate.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealSet
    {
        public int Id { get; set; }
        public int Demand_Id { get; set; }
        public int Supply_Id { get; set; }
    
        public virtual DemandSet DemandSet { get; set; }
        public virtual SupplySet SupplySet { get; set; }
    }
}
