//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restate.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEstateFilterSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RealEstateFilterSet()
        {
            this.DemandSets = new HashSet<DemandSet>();
        }
    
        public int Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemandSet> DemandSets { get; set; }
        public virtual RealEstateFilterSet_ApartmentFilter RealEstateFilterSet_ApartmentFilter { get; set; }
        public virtual RealEstateFilterSet_HouseFilter RealEstateFilterSet_HouseFilter { get; set; }
        public virtual RealEstateFilterSet_LandFilter RealEstateFilterSet_LandFilter { get; set; }
    }
}
